# L2 parity test: encode each Julia value, assert byte-equal to the
# canonical CBOR bytes generated by ciborium (the SurrealDB server's
# crate). Fixtures live at test/fixtures/cbor/native.toml; regenerate
# via `cd test/fixtures/cbor/gen && cargo run > ../native.toml`.

using SurrealDB.SurrealCBOR
using SurrealDB.SurrealCBOR: encode, Tagged
using Test
using TOML

const _FIXTURE_FILE = joinpath(@__DIR__, "fixtures", "cbor", "native.toml")

# label → Julia value the test encodes. Names match the labels emitted
# by test/fixtures/cbor/gen/src/main.rs.
const _CASES = Dict{String, Any}(
    # Unsigned ints
    "uint_0"           => 0,
    "uint_1"           => 1,
    "uint_10"          => 10,
    "uint_23"          => 23,
    "uint_24"          => 24,
    "uint_25"          => 25,
    "uint_100"         => 100,
    "uint_255"         => 255,
    "uint_256"         => 256,
    "uint_1000"        => 1000,
    "uint_65535"       => 65535,
    "uint_65536"       => 65536,
    "uint_1_000_000"   => 1_000_000,
    "uint_u32max"      => UInt32(0xffff_ffff),
    "uint_2pow32"      => UInt64(2)^32,
    "uint_1e12"        => 1_000_000_000_000,
    "uint_i64max"      => typemax(Int64),
    "uint_u64max"      => typemax(UInt64),

    # Negative ints
    "nint_-1"          => -1,
    "nint_-10"         => -10,
    "nint_-24"         => -24,
    "nint_-25"         => -25,
    "nint_-100"        => -100,
    "nint_-1000"       => -1000,
    "nint_i64min"      => typemin(Int64),

    # Floats
    "float_1.1"        => 1.1,
    "float_-4.1"       => -4.1,
    "float_1e300"      => 1.0e+300,
    "float_0.0"        => 0.0,
    "float_-inf"       => -Inf64,
    "float_inf"        => Inf64,

    # Simple
    "bool_false"       => false,
    "bool_true"        => true,
    "null"             => nothing,

    # Text
    "text_empty"       => "",
    "text_a"           => "a",
    "text_ietf"        => "IETF",
    "text_escape"      => "\"\\",
    "text_u_umlaut"    => "ü",
    "text_water"       => "水",

    # Bytes
    "bytes_empty"      => UInt8[],
    "bytes_1234"       => UInt8[0x01, 0x02, 0x03, 0x04],

    # Arrays
    "array_empty"      => Any[],
    "array_123"        => [1, 2, 3],
    "array_nested"     => Any[1, [2, 3], [4, 5]],
    "array_1_to_25"    => collect(1:25),

    # Maps
    "map_empty"        => Dict{Any,Any}(),
    "map_int_pairs"    => Dict(1 => 2, 3 => 4),
    "map_a1_b23"       => Dict{Any,Any}("a" => 1, "b" => [2, 3]),
    "map_aa2_b1_sorted" => Dict("aa" => 2, "b" => 1),

    # Tagged passthrough
    "tag_0_datetime_string" => Tagged(UInt64(0), "2013-03-21T20:04:00Z"),
    "tag_6_none"            => Tagged(UInt64(6), nothing),
)

@testset "L2 parity — vs ciborium (Rust server's CBOR crate)" begin
    fixtures = TOML.parsefile(_FIXTURE_FILE)

    # Every fixture label must have a Julia case; every Julia case must
    # have a fixture. Drift in either direction is a test failure.
    fix_labels  = Set(keys(fixtures))
    case_labels = Set(keys(_CASES))
    @test fix_labels == case_labels

    for (label, value) in _CASES
        haskey(fixtures, label) || continue   # surfaced above
        expected = lowercase(fixtures[label]["hex"])
        actual   = bytes2hex(encode(value))
        @test (label, actual) == (label, expected)
    end
end
